// Nameing: PAGE_ACTION_STATUS

export const APP_LOGIN_SET = 'APP_LOGIN_SET'
export const APP_LOGOUT_SET = 'APP_LOGOUT_SET'

export const LOGIN_EDITFORM_CHANGE = 'LOGIN_EDITFORM_CHANGE'
export const LOGIN_LOGIN_LOAD = 'LOGIN_LOGIN_LOAD'
export const LOGIN_LOGIN_SUCCEED = 'LOGIN_LOGIN_SUCCEED'
export const LOGIN_LOGIN_FAIL = 'LOGIN_LOGIN_FAIL'

export const ADMIN_OPENSUBMENU_CHANGE = 'ADMIN_OPENSUBMENU_CHANGE'
export const ADMIN_TOGGLESIDER_CHANGE = 'ADMIN_TOGGLESIDER_CHANGE'
